### ISSUE TITLE
Changing background image for Plasma 5 desktop not working

### ISSUE THREAD

**Issue by nedy13** [onli/izulu#8]
It is not possible to use izulu for Plasma desktop environments.
I researched a lot to find a script solution to change the background image.

I find a solution here [Link](https://www.kubuntuforums.net/showthread.php?66762-Right-click-wallpaper-changer&p=387392&viewfull=1#post387392)

This shell command sets the wallpaper, but I am unable to quote this string the correct way to implement it myself.

```
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///file:///home/nedy/.izulu/izulucurrent")}'
```

**Comment by onli** [comment]
I don't have a Plasma 5 desktop at hand to test this easily. But I can help with the escaping. The code you show looks correctly quoted (as in, having the right quotation marks). But we need to echo it, as a complete string. That means we have to add quotation marks at the outer layer, and escape the quotation marks inside:

    echo "qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");d.writeConfig(\"Image\", \"file://$HOME/.izulu/izulucurrent\")}'"

However, we can't integrate it into izulu that way. We expect `getWPCommand()` to emit a string that is the command where the path to the file can be appended. But here it has to be placed inside the string, for the closing `")}`. We would need to change our system to emit a string where we have a placeholder for the file that gets then replaced, and the resulting command executed. Might work

It should be on KDE to provide a proper cli interface that does not break conventions. That's annoying, and that's why KDE is not supported so far. If doing a workaround I would need you to test this, I don't want to make that change if it not at least results in KDE working properly :)

The line in `getWPCommand` would look like this:

    echo "qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");d.writeConfig(\"Image\", \"file:///file://PLACEHOLDER\")}'"

When we call `WPCOMMAND` in `setImage`, we'd have to change it to:

    ${WPCOMMAND/PLACEHOLDER/"$HOME/.izulu/izulucurrent"}

We'd also have to change the other lines in getWPCommand to use the placeholder system, but that can be a later commit. Could you test it with that explanation already, or shall I upload a modified script version?

**Comment by nedy13** [comment]
I tried to add the function, but it seems that something with quoting is not working.

Script changes:
```
getWPCommand() {
...
elif [ x"$XDG_CURRENT_DESKTOP" = x"MATE" ];then
        gsettings set org.mate.background picture-options "stretched"
        echo "gsettings set org.mate.background picture-filename"
elif [ x"$XDG_CURRENT_DESKTOP" = x"KDE" ];then
        echo "qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = \"org.kde.image\";d.currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");d.writeConfig(\"Image\", \"file://PLACEHOLDER\")}'"
```

```
setImage() {
...
set -x    
    cp "$tmpimage" "$HOME"/.izulu/izulucurrent
    rm "$tmpimage"
    if [  "${WPCOMMAND:${#WPCOMMAND}-1}" == "/" ];then
        ${WPCOMMAND}"$HOME/.izulu/izulucurrent" &
    else
        #$WPCOMMAND "$HOME/.izulu/izulucurrent" &
        echo ${WPCOMMAND/PLACEHOLDER/"$HOME/.izulu/izulucurrent"}
        ${WPCOMMAND/PLACEHOLDER/"$HOME/.izulu/izulucurrent"}
    fi
set +x
```

Output:
else
+ echo qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript ''\''var' allDesktops = 'desktops();print' '(allDesktops);for' '(i=0;i<allDesktops.length;i++)' '{d' = 'allDesktops[i];d.wallpaperPlugin' = '"org.kde.image";d.currentConfigGroup' = 'Array("Wallpaper",' '"org.kde.image",' '"General");d.writeConfig("Image",' '"file:///home/nedy/.izulu/izulucurrent")}'\'''
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///home/nedy/.izulu/izulucurrent")}'
+ qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript ''\''var' allDesktops = 'desktops();print' '(allDesktops);for' '(i=0;i<allDesktops.length;i++)' '{d' = 'allDesktops[i];d.wallpaperPlugin' = '"org.kde.image";d.currentConfigGroup' = 'Array("Wallpaper",' '"org.kde.image",' '"General");d.writeConfig("Image",' '"file:///home/nedy/.izulu/izulucurrent")}'\'''
Invalid number of parameters
+ set +x

I don't know where the error message comes from **Invalid number of parameters**.

The result of echo is correct and works like expected when I execute it directly in the shell. The string substitution works also correct. I tried a lot, but no idea at the moment. I am at the beginner level of bash / shell scripting.

**Comment by onli** [comment]
Please try it with https://gist.github.com/onli/a002cfbc623a950df0e7cae643b0b317. It should have no escape error. If it just fails to detect that KDE is running, please show me the output of `echo $XDG_CURRENT_DESKTOP`. For me, the command to change the wallpaper itself is throwing an error ("Cannot find 'org.kde.PlasmaShell.evaluateScript' in object /PlasmaShell at org.kde.plasmashell"), but that might be because I don't have KDE fully installed. If the script is correct this should work for you.

**Comment by onli** [comment]
@nedy13 ?

**Comment by nedy13** [comment]
Sorry...
I tried it and it causes the same error message. I also recognized that the background only changes when you try to set a new picture as background. So you must execute this command twice. The first call without a path to clear the background and the second call with the whether background.

I give it up at the moment. It was a try to add Plasma support, but unfortunately it doesn't work. From my point of view, you can close this issue.

Thanks for your help.

**Comment by onli** [comment]
Okay. No problem. If you or someone else stumbles over a way to set the background programmatically with a single command, feel free to re-open this issue.

**Comment by vamartid** [comment]
I stumbled on this issue while trying to change wallpaper with cron on plasma.
I used the script provided [here](https://github.com/mk-fg/pulseaudio-mixer-cli/issues/17) and replaced the proccess with PlasmaShell.
probably before line https://gist.github.com/onli/a002cfbc623a950df0e7cae643b0b317#file-izulu-1-1-L456
```
pid=$(pgrep -xn plasmashell)\
  && export DBUS_SESSION_BUS_ADDRESS="$(grep -ao -m1 -P '(?<=DBUS_SESSION_BUS_ADDRESS=).*?\0' /proc/"$pid"/environ)"
```
Be aware that I didn't install your izulu just had that issue.

**Comment by onli** [comment]
Hey @vamartid, thanks for the comment back then! I just noticed I never reacted, sorry!

I do not get how to combine this though. The command you describe set the `DBUS_SESSION_BUS_ADDRESS`. Afterwards the `qdbus` command from the first comment in this issue should work?
